service: smart-task-manager

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-5
  stage: dev
  environment:
    SUPABASE_URL: ${env:SUPABASE_URL}
    SUPABASE_KEY: ${env:SUPABASE_KEY}

functions:
  getTasks:
    handler: src/handlers/tasks.getTasks
    events:
      - http:
          path: /tasks
          method: get
          cors: true

  createTask:
    handler: src/handlers/tasks.createTask
    events:
      - http:
          path: /tasks
          method: post
          cors: true

  updateTask:
    handler: src/handlers/tasks.updateTask
    events:
      - http:
          path: /tasks/{id}
          method: put
          cors: true

  deleteTask:
    handler: src/handlers/tasks.deleteTask
    events:
      - http:
          path: /tasks/{id}
          method: delete

  handleOptionsRoot:
    handler: src/handlers/options.handleOptions
    events:
      - http:
          path: tasks
          method: options
          cors: true

  handleOptionsWithId:
    handler: src/handlers/options.handleOptions
    events:
      - http:
          path: tasks/{id}
          method: options
          cors: true

  viewTask:
    handler: src/handlers/tasks.viewTask
    events:
      - http:
          path: /tasks/view/{task_id}
          method: get
          cors: true

  analyzeTask:
    handler: src/handlers/aiAnalysis.analyzeTask
    events:
      - http:
          path: /tasks/analyze/{task_id}
          method: post
          cors: true
    environment:
      GEMINI_API_KEY: ${env:GEMINI_API_KEY}
    timeout: 30

plugins:
  - serverless-esbuild
  - serverless-dotenv-plugin
